# Generated by Django 3.1.2 on 2020-11-02 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0004_auto_20201101_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiletwo',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='profiletwo',
            name='modified',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
